name: Dependabot Auto Merge

on:
  pull_request_target:
    types: [labeled]

jobs:
  auto:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        name: 自动合并dependabot通过ci测试的请求
        with:
          target: minor
          github-token: ${{ secrets.PAT_REPO_ADMIN }}
